trigger: 
# runs on push based
 branches:
   include:
     - main
     - feature

     
# runs on pull based
# pr:
#  branches:
#    include:
#      - main
#      - feature

# agent pool name
pool: poc

variables:
  directory:  

stages:
  - stage:
    displayName: 
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
