trigger:
  branches:
    include:
      - main

pool: poc

stages:
  - stage: TerraformStage
    displayName: "Terraform Deployment"
    jobs:
      - job: TerraformInit
        displayName: "Terraform Init"
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              backendServiceArm: 'azurerm-service-connection'
              backendAzureRmResourceGroupName: 'rg-backend'
              backendAzureRmStorageAccountName: 'stgbackend25'
              backendAzureRmContainerName: 'backendcont'
              backendAzureRmKey: 'terraform.tfstate'

      - job: TerraformPlanApply
        displayName: "Plan & Apply"
        dependsOn: TerraformInit
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: 'azurerm-service-connection'

          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)/terraform'
              environmentServiceNameAzureRM: 'azurerm-service-connection'


      - job: SSHConnect
        displayName: 'SSH Connect & Install Nginx'
        dependsOn: TerraformPlanApply
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'ssh-service-connection'
              runOptions: 'inline'
              inline: |
                sudo apt update -y
                sudo apt install nginx -y
                sudo systemctl enable nginx
                sudo systemctl start nginx
              readyTimeout: '20000'

      - job: DeployCode
        displayName: 'Deploy Code'
        dependsOn: SSHConnect
        steps:
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ssh-service-connection'
              sourceFolder: '$(System.DefaultWorkingDirectory)/src'
              contents: 'index.html'
              readyTimeout: '20000'
